### ISSUE TITLE
Empty/blank settings value causes func.exe insufficient memory error

### ISSUE THREAD

**Issue by TroyWitthoeft** [Azure/azure-functions-core-tools#1732]
Creating a new Azure Functions project in VSCode and adding a empty local.settings.json value `"":""` 

![image](https://user-images.githubusercontent.com/1102958/71382836-b5516d00-25a7-11ea-99af-73ba8dc490e2.png)

and starting a debug sessions causes func.exe to fail with the following error `Insufficient memory to continue the execution of the program.`

![image](https://user-images.githubusercontent.com/1102958/71382679-f1380280-25a6-11ea-812c-6a3eb49e38a7.png)

Obviously, we shouldn't be entering empty values into our `local.settings.json` file, but I could see folks doing this as boilerplate, intending to fill them out later and never returning.  How does func.exe handle empty settings/environment values?  Is there a way we could ignore these values? 
 If not, could we detect them and update the error message?  Willing to make a PR here.  The error message had me closing all fifty of my browser tabs to free up memory!  😝 

Created a repro repo here. 
https://github.com/TroyWitthoeft/AzureFunctionsCoreToolsEmptySettingBug

Found another poor soul on SO having the same issue here
https://stackoverflow.com/questions/59246489/azure-function-insufficient-memory-to-continue-the-execution-of-the-program#comment105103825_59246489

Repro steps
1. Launch VSCode
2. Create a new Azure Functions project using the Azure Functions Extension
     a. Language = C#
     b. Template = HttpTrigger
3. Add an empty value to the values collection in  `local.settings.json`, such as `"":""`
4. Start a debug session. 
    
Environment
OS: Win 10
VSCode: 1.40.2 + Azure Functions Extension v0.20.1
Azure Func Core tools: 3.0.2009

**Comment by ahmedelnably** [comment]
@TroyWitthoeft thanks for finding this issue, we do accept contributions from the community and we will be happy reviewing and merging your PR :)

**Comment by TroyWitthoeft** [comment]
PR #1735 created.

**Comment by TroyWitthoeft** [comment]
I know it's only a small change for me, and a few folks, but I'm concerned PR 1735 might not make it in?    The dev branch is being updated underneath it.

**Comment by PdroCorrea** [comment]
Sad that this felt through the cracks somewhere there, just spent the last 6h investigating this until your StackOverflow question @TroyWitthoeft , thank you very much!

**Comment by TroyWitthoeft** [comment]
@PdroCorrea, sorry to hear that.  I believe that @ahmelsayed had this bug fix pushed in a while back?   I can see the change on [line 247](https://github.com/Azure/azure-functions-core-tools/blob/aacc8c22eeddd53bd14af260e6cd18cbf276af49/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs#L247) of the current version of `azure-functions-core-tools/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs`   

So the fix should be in.  Update Azure Functions Core tools?

**Comment by samsmithnz** [comment]
I just ran into this today with a .NET 6 function - so still not resolved.

**Comment by ejizba** [comment]
Thanks for the ping @samsmithnz. Looks like this wasn't cherry-picked to the v3 and v4 versions of the cli. I'll get it addressed

**Comment by ejizba** [comment]
Yes sorry GitHub normally closes the issue automatically when I link it in the PR, not sure what happened here. This has been fixed and can be closed
