### ISSUE TITLE
Template list for Azure Functions in Visual Source Code shows HTTP triggers only

### ISSUE THREAD

**Issue by salemrartin** [Azure/azure-functions-core-tools#2338]
Hello,
I updated this morning to the latest azure-functions-core-tools 3.0.3160 and since then the list of Azure functions template in Visual Source Code has shrunk to one template only! HTTP trigger(s) from OpenAPI V2/V3
I am able to reproduce this issue on a brand new MacOS installation! 
Can someone look into this? I am trying to downgrade to the previous 3.0.996 version but I haven't been able to do that so far

Please help

**Comment by ankitkumarr** [comment]
Hi @salemrartin,

Thank you for reporting this! We are taking a look and will likely have it resolved soon.

**Comment by salemrartin** [comment]
Hi @ankitkumarr,
Thank you for your prompt response! I am relatively new to Azure Functions development and as you can see I am currently blocked.
I _think_ my problem will go away if I can roll back to the previous azure-functions-core-tools 3.0.2996. If so, can you shed some light on how to do so via brew command line? I am unable to find a way to do so
I am using a Mac just so that you know

Much appreciate any guidance on this!

**Comment by ankitkumarr** [comment]
@salemrartin, the templates don't actually come from the core tools directly. But the good news is that the fix is deployed (thanks to @yojagad and @soninaren).

You may need to clear your template cache for it to work immediately. The two cache that seemed to fix it for me were, when I removed --

In mac,
`$HOME/Library/Application Support/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/` and
`~/.templateengine/AzureFunctions-VSCodeExtension`

In windows,
`%AppData%\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates` and
`%USERPROFILE%/.templateengine/AzureFunctions-VSCodeExtension`

Please let me know if clearing these directories don't work.

Additionally, there will be a new release of the VS code extension in a couple of days that should fix this without requiring you to clear the above cache.

cc: @ejizba (thanks for your help)

**Comment by salemrartin** [comment]
You guys are rock stars! Clearing the template cache in both folders fixed the problem!
Thank you @ankitkumarr & @ejizba so much for resolving a problem within less than 12 hours!

**Comment by BorCob** [comment]
@ankitkumarr Unfortunately, clearing the cache (2 MacOS installs in my case) didn't solve anything. 

Please have a look here: https://github.com/microsoft/vscode-azurefunctions/issues/2588

**Comment by ejizba** [comment]
We just released v1.1.0 of the extension, including a fix for this (without needing to clear the cache).
