### ISSUE TITLE
Azure Functions Core Tools v4 unable deploy to Kubernetes

### ISSUE THREAD

**Issue by doggy8088** [Azure/azure-functions-core-tools#2825]
```txt
G:\Projects\funapp2>func --version
4.0.3928

G:\Projects\funapp2>dotnet --version
6.0.100
```

Here are the steps to reproduce the problem.

```sh
mkdir funapp2 && cd funapp2
func init --worker-runtime dotnetIsolated --docker
func new -t "HttpTrigger" -n "Login" -a "anonymous"
```

Modify the `Dockerfile` file as below:

```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS installer-env

COPY . /src/dotnet-function-app
RUN cd /src/dotnet-function-app && \
    mkdir -p /home/site/wwwroot && \
    dotnet publish *.csproj --output /home/site/wwwroot

# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/dotnet-isolated:3.0-dotnet-isolated5.0-appservice
FROM mcr.microsoft.com/azure-functions/dotnet-isolated:3.0-dotnet-isolated5.0
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]
```

Build & Push image

```sh
docker build -t willh/funapp2:latest .
docker push willh/funapp2:latest
```

Deploy my function app with `--dry-run`

```sh
func kubernetes deploy --name funapp2 --service-type NodePort --image-name willh/funapp2 --dry-run
```

There is only **Secret** been created.

```sh
data:
  AzureWebJobsStorage: VXNlRGV2ZWxvcG1lbnRTdG9yYWdlPXRydWU=
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0LWlzb2xhdGVk
apiVersion: v1
kind: Secret
metadata:
  name: funapp2
---
```

Where is the other YAML of the deployment?

**Comment by MACEL94** [comment]
upvote, i am encountering the same bug

**Comment by doggy8088** [comment]
@MACEL94 It seems nobody watching this repo. I reported a few issues that is been stalled for more than 1 month.

**Comment by jammehcow** [comment]
I'm intending on deploying a set of .NET 6 functions to a kubernetes cluster early next year. Would be great to have this fixed by then!

**Comment by garybond** [comment]
Just confirming still an issue and now an issue for us.
net6 & func --version 4.0.3971
We are deploying secrets independently before running func kubernetes deploy, so different to OP. I'm not expecting ans secrets yaml in the output.
--dry-run > output.yaml generates completely empty output file

**Comment by f1x3d** [comment]
I created a PR to resolve this issue inside the functions tooling: #3000 

In the meantime, if you want an immediate fix on your project's side, I also created a helper program that does that. 
It is published as a [NuGet package Az.Functions.MetadataToJson](https://www.nuget.org/packages/Az.Functions.MetadataToJson) ([repo on GitHub](https://github.com/f1x3d/Az.Functions.MetadataToJson))

Just add a reference to it in your project file and it should make the `func kubernetes deploy` work as expected.

**Comment by SOFSPEEL** [comment]
I added Az.Functions.MetadataToJson to my project and am still getting just a secret in deploy.yaml
using this command

`func kubernetes deploy --image-name "blah.azurecr.io/resizer:v1" --dry-run > deploy.yaml  --name resizer`

deploy.yaml

```
data:
  AzureWebJobsStorage: blah
  FUNCTIONS_WORKER_RUNTIME: blah
  APPINSIGHTS_INSTRUMENTATIONKEY: blah
  AppConfigEndpoint: blah
  AppConfigConnectionString: blah
apiVersion: v1
kind: Secret
metadata:
  name: resizer
---
```
I also tried the  --dotnet-isolated approach and it had same issue.

My csproj is as follows:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <Configurations>Debug;Release;Local</Configurations>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Az.Functions.MetadataToJson" Version="1.0.1" />
    <PackageReference Include="Azure.Data.AppConfiguration" Version="1.2.0" />
    <PackageReference Include ="Azure.Identity" Version="1.5.0" />
    <PackageReference Include="AzureFunctions.Autofac" Version="4.0.3" />
    <PackageReference Include="Imageflow.AllPlatforms" Version="0.7.24" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

Does this perhaps have something to do with my project being net6.0

**Comment by SOFSPEEL** [comment]
@

> ```
> G:\Projects\funapp2>func --version
> 4.0.3928
> 
> G:\Projects\funapp2>dotnet --version
> 6.0.100
> ```
> 
> Here are the steps to reproduce the problem.
> 
> ```shell
> mkdir funapp2 && cd funapp2
> func init --worker-runtime dotnetIsolated --docker
> func new -t "HttpTrigger" -n "Login" -a "anonymous"
> ```
> 
> Modify the `Dockerfile` file as below:
> 
> ```dockerfile
> FROM mcr.microsoft.com/dotnet/sdk:6.0 AS installer-env
> 
> COPY . /src/dotnet-function-app
> RUN cd /src/dotnet-function-app && \
>     mkdir -p /home/site/wwwroot && \
>     dotnet publish *.csproj --output /home/site/wwwroot
> 
> # To enable ssh & remote debugging on app service change the base image to the one below
> # FROM mcr.microsoft.com/azure-functions/dotnet-isolated:3.0-dotnet-isolated5.0-appservice
> FROM mcr.microsoft.com/azure-functions/dotnet-isolated:3.0-dotnet-isolated5.0
> ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
>     AzureFunctionsJobHost__Logging__Console__IsEnabled=true
> 
> COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]
> ```
> 
> Build & Push image
> 
> ```shell
> docker build -t willh/funapp2:latest .
> docker push willh/funapp2:latest
> ```
> 
> Deploy my function app with `--dry-run`
> 
> ```shell
> func kubernetes deploy --name funapp2 --service-type NodePort --image-name willh/funapp2 --dry-run
> ```
> 
> There is only **Secret** been created.
> 
> ```shell
> data:
>   AzureWebJobsStorage: VXNlRGV2ZWxvcG1lbnRTdG9yYWdlPXRydWU=
>   FUNCTIONS_WORKER_RUNTIME: ZG90bmV0LWlzb2xhdGVk
> apiVersion: v1
> kind: Secret
> metadata:
>   name: funapp2
> ---
> ```
> 
> Where is the other YAML of the deployment?

I was getting the same problem, issue was that my **image was not properly built**.

**Comment by f1x3d** [comment]
@SOFSPEEL The `mcr.microsoft.com/azure-functions/dotnet:4` image you mentioned is for non-isolated function apps.

The issue described here only affects isolated functions since the `functions.json` file is not generated for isolated funcs during the build process, and the current version of CLI tools uses information from this file to generate deploy yaml.

Though [the band-aid mentioned above](https://github.com/Azure/azure-functions-core-tools/issues/2825#issuecomment-1079981529) should also work then you're running isolated functions inside Docker images like `mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated6.0`

**Comment by SOFSPEEL** [comment]
So still can't get the correct deployment.

I changed Docker to use "isolated"

```
FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated6.0

ARG CONFIGURATION
# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/dotnet:4-appservice
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY . bin/Debug/net6.0/publish /home/site/wwwroot/
```

I added band aid to csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Az.Functions.MetadataToJson" Version="1.0.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.8.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

I'm running version
```
funapp2 % func -version
4.0.4653
```

when I run:
```
 funapp2 % func kubernetes deploy --csharp --name junk --registry checkservicedev --write-configs
Running 'docker build -t checkservicedev/junk:latest ..
/RiderProjects/CharityDynamics.Gateway/funapp2'...done
Configuration written to functions.yaml%  
```

The resultant output is:
```
data:
  AzureWebJobsStorage:    blah
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0LWlzb2xhdGVk
apiVersion: v1
kind: Secret
metadata:
  name: junk
---
```

and to be clear I'm expecting the Azure Core Tools to be generating stuff like: 
AzureWebJobsSecretStorageType = true

https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobskubernetessecretname

`Indicates the Kubernetes Secrets resource used for storing keys. Supported only when running in Kubernetes. Requires that AzureWebJobsSecretStorageType be set to kubernetes. When AzureWebJobsKubernetesSecretName isn't set, the repository is considered read-only. In this case, the values must be generated before deployment. The [Azure Functions Core Tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local) generates the values automatically when deploying to Kubernetes.
`

Am I running **func kubernetes deploy** incorrectly to be able to get the proper deployment for azure functions is k8s?

**Comment by andrasdevs** [comment]
It seems that the PR is stale, it is required to have more tests as @FinVamp1 commented.
Our deployment is blocked by this issue. 
Any plans @khkh-ms @michaelpeng36 @AnatoliB to merge the PR in the next weeks or should we move to a full manual deployment?

**Comment by claudio-cauchi** [comment]
We are blocked by this issue too.  @khkh-ms @michaelpeng36 @AnatoliB can we have a status update on this please?

**Comment by jwstauber2** [comment]
Bump.  Also blocked by this.

**Comment by darthmolen** [comment]
We need all the YAML files output in a dry-run for the "kubernetes deploy" for a different reason. We are running our deployments to kubernetes (AKS) using HELM and Azure Keyvault CSI Driver integration, so we need to get the YAML out to put them in a more realistic scenario for CI/CD deployments.... the dry-run for the install command outputs all the YAML files, but the deploy does not, making it hard to implement this in an enterprise environment.

**Comment by sdahlbac** [comment]
Same issue is also a problem with node

**Comment by abaturovskyi** [comment]
Experiencing the same problem with node

**Comment by mbauer-dilt** [comment]
It's 2025 and this issue seems to still persist. :(

**Comment by zeezeewhy** [comment]
wondering if there is a template somewhere so I can manually modify it to get things moving.

**Comment by liliankasem** [comment]
Took a look into this and it looks like the reason its not deploying is because it's not finding a functions.metadata or functions.json file:

https://github.com/Azure/azure-functions-core-tools/blob/40a19e11f70f3c9aaefb3911a8581014ec748413/src/Cli/func/Helpers/DockerHelpers.cs#L67

[script](https://github.com/Azure/azure-functions-core-tools/blob/40a19e11f70f3c9aaefb3911a8581014ec748413/src/Cli/func/StaticResources/print-functions.sh)

None of the new models for Functions use functions.json, and functions.metadata isn't even always present for the dotnet worker (depending on how you build it). I think the Kubernetes extensions has sadly not been maintained as the product has grown and changed. 

This item will require a redesign of how the command works. Looking through the code, I think the only reason the metadata is needed is to get the function name and type so that's what we would need to solve here.

I'll follow up with the team on next steps for this and the Kubernetes extension.

#### Additional details that might help design

The function name is used to generate environment variables for enabled functions e.g. `AzureFunctionsJobHost__functions__0 = MyHttp`. 

https://github.com/Azure/azure-functions-core-tools/blob/40a19e11f70f3c9aaefb3911a8581014ec748413/src/Cli/func/Kubernetes/KubernetesHelper.cs#L119-L124

https://github.com/Azure/azure-functions-core-tools/blob/40a19e11f70f3c9aaefb3911a8581014ec748413/src/Cli/func/Kubernetes/KubernetesHelper.cs#L133

And to generate the function keys:

https://github.com/Azure/azure-functions-core-tools/blob/40a19e11f70f3c9aaefb3911a8581014ec748413/src/Cli/func/Kubernetes/KubernetesHelper.cs#L220

And the function type is used to find http vs non-http functions which require different deployments, or additional service:

http:

https://github.com/Azure/azure-functions-core-tools/blob/40a19e11f70f3c9aaefb3911a8581014ec748413/src/Cli/func/Kubernetes/KubernetesHelper.cs#L124-L127

non-http:

https://github.com/Azure/azure-functions-core-tools/blob/40a19e11f70f3c9aaefb3911a8581014ec748413/src/Cli/func/Kubernetes/KubernetesHelper.cs#L133-L136

The design can initially focus on getting the function names and type to `GetFunctionsDeploymentResources` without depending on function.json or function.metadata.
