### ISSUE TITLE
System.Private.CoreLib: Could not load file or assembly 'Microsoft.WindowsAzure.Storage

### ISSUE THREAD

**Issue by hanislovingit** [Azure/azure-functions-core-tools#412]
I just updated VS Professional from v15.6.2 to v15.6.3 earlier today. After the update, I get a runtime error when running my Azure function. Prior to the update, it was running just fine.

 System.Private.CoreLib: Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=9.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=9.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

Here's a screenshot

![2018-03-19_17h57_55](https://user-images.githubusercontent.com/6548693/37627319-dde6f854-2ba1-11e8-9748-775bd346b03f.png)

My Azure function's dependency hierarchy looks like this

![2018-03-19_18h17_14](https://user-images.githubusercontent.com/6548693/37627320-ddfa7834-2ba1-11e8-9b89-f63d7fd1d7a8.png)

I tried restarting VS, restarting my pc. None worked.

**Comment by MV10** [comment]
Same error while migrating our v1 apps to v2, except I'm on VS 15.6.4, Functions SDK 1.0.12, and webjobs.* 3.0.0-beta5 across the board. According to object browser, the storage 9.1.0 DLL is in the netstandard 1.3 cache, and I see it was copied into the project's `bin` folder.

![image](https://user-images.githubusercontent.com/794270/38164002-78967ffa-34cb-11e8-8457-805abb1ec4be.png)

![image](https://user-images.githubusercontent.com/794270/38164115-71423940-34cd-11e8-9403-13874158b2e8.png)

**Comment by MV10** [comment]
Based on this gentleman's experience https://github.com/Azure/azure-functions-core-tools/issues/322#issuecomment-352233979 it sounds as if the CLI might be dependent on an incompatible version?

**Comment by MV10** [comment]
Running the latest `func` beta doesn't help, same error (tools 220.0.0-beta.0, runtime 2.0.11651.0).

**Comment by MV10** [comment]
If I'm looking at this correctly, it looks like [this](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj#L48) reference to version 8.6.0 is probably the culprit since the CLI [csproj](https://github.com/Azure/azure-functions-core-tools/blob/master/src/Azure.Functions.Cli/Azure.Functions.Cli.csproj#L51) depends on that assembly.

**Comment by crnd** [comment]
As @MV10 pointed out there already is 8.6.0 of WindowsAzure.Storage included in your project. The easiest way to get rid of the issue is to use that version for now if your code is not depending on a newer version.

**Comment by kvinther** [comment]
I have the same issue only for "Microsoft.Extensions.Configuration". I am referencing 2.0.1 in my DLL, which is the exact same version used by the Functions SDK (1.0.13). My unit tests all pass with flying colors, so this seems to be an issue in the Functions Tools. All mentions of Microsoft.Extensions.Configuration in the deps.json files point to 2.0.1. My DLL points to the config DLL at "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.configuration\2.0.1".

Any suggestions as how to proceed?

**Comment by ahmelsayed** [comment]
This should be fixed in the latest v2 release

**Comment by wboevink** [comment]
@ahmelsayed: Sadly no, still have the same error with the latest version

System.Private.CoreLib: Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=9.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=9.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

Using

Visual Studio 2017 15.7.1
Azure Functions and Web Jobs Tools 15.0.40502.0

**Comment by stevenlivz** [comment]
I have the same error as @wboevink - i have tried a few alternatives. Some guidance would be greatly appreciated. A gist of the generated dependencies is [here](https://gist.github.com/stevenlivz/c24f3d5278d0cf65c3b4cb29ba970a44)

I am using the latest VS Mac alpha as below:

Visual Studio Enterprise 2017 for Mac (Preview)
Version 7.6 Preview (7.6 build 711)
Installation UUID: 71d6029a-504c-4497-994e-cf0311359b9f
Runtime:
	Mono 5.12.0.226 (2018-02/9824e260f56) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 512000226

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.0.2
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.2
	2.0.0
	1.0.0-preview2-003148
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.3 (14154)
Build 9E145

Xamarin.Mac
Version: 4.5.0.280 (Visual Studio Enterprise Trial)
Hash: e85a7be8
Branch: master
Build date: 2018-05-03 11:35:01-0400

Xamarin.iOS
Version: 11.11.0.280 (Visual Studio Enterprise Trial)
Hash: e85a7be8
Branch: master
Build date: 2018-05-03 11:35:00-0400

Xamarin.Android
Version: 8.3.0.19 (Visual Studio Enterprise Trial)
Android SDK: /Users/livz/Library/Android/sdk
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 23.0.1

Java SDK: /usr
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 706000711
Git revision: 634060c6c105fd3ee36678fe547680fd258cbf45
Build date: 2018-05-04 16:11:06-04
Xamarin extensions: c6720450018cb69a3da7c6d0aa0715c013783595
Build lane: monodevelop-lion-master

Operating System
Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Fri Apr 13 19:32:32 PDT 2018
    root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
Internet of Things (IoT) development (Preview) 7.1

**Comment by eslsys** [comment]
@ahmelsayed: Also the same as @wboevink with the same VS and Azure Functions versions. Very frustrating

**Comment by evandropaula** [comment]
`func host start` **does not** solve the issue, it may seem to work depending on the Azure Function dependencies because it starts runtime version on 1.x by default. You can observe that in the console log: 
Starting Host (HostId=e505cc11c08147b69cd4f6a95d861b6e, **Version=1.0.10826.0**, ProcessId=25444, Debug=False, Attempt=0)

**Comment by Dhanaselvam** [comment]
[6/7/2018 3:26:00 PM] System.Private.CoreLib: Exception while executing function
: TimerTriggerCSharp. Patient.CredentialStore.AzureFunctions: Could not load fil
e or assembly 'Microsoft.WindowsAzure.Storage, Version=9.2.0.0, Culture=neutral,
 PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exce
ption from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or
assembly 'Microsoft.WindowsAzure.Storage, Version=9.2.0.0, Culture=neutral, Publ
icKeyToken=31bf3856ad364e35'.

Am also facing the same problem i have tried with downgrading webjobs beta , stable versions still couldn't solve the issues to integrate azure table storage with the azure functions .. ;( ;(

**Comment by mithunshanbhag** [comment]
Seems like the solution is to downgrade WindowsAzure.Storage nuget to version 8.6.0 as mentioned here:
https://github.com/Azure/azure-functions-core-tools/issues/322

This worked for me.

**Comment by Toothless-NIghtFury** [comment]
@mithunshanbhag  yah the webjobs beta 3.X not works with the table storage version  > 8.6

**Comment by delroyh** [comment]
A little late to the party, but I just had this issue with VS 15.7 and Azure Function Cli 2.7 (I think, I forgot to verify before updating). After updating to VS 15.8.6 and Azure Function Cli 2.8.1 the problem appears to be resolved.

**Comment by sharifmamun** [comment]
I was having the same issue on a blob triggered v2 Azure function. Upgrading to the latest, Azure Function Cli version 2.10.1 and VS Professional 2017 15.8.7 worked fine for me. @delroyh thanks for your post here.
