### ISSUE TITLE
func init returns No templates or subcommands found matching: 'func'.

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-functions-core-tools#4399]
### Version

`4.0.7030`

### Description

I have core tools version `4.0.7030`, which I believe is the latest. I'm trying to run `func init LocalFunctionProj --worker-runtime dotnet-isolated --docker --target-framework net8.0`. The command returns 

```
No templates or subcommands found matching: 'func'.
Did you mean one of the following templates?
   dotnet new sln
   dotnet new mvc
   dotnet new grpc
   dotnet new nunit
   dotnet new xunit

To list installed templates similar to 'func', run:
   dotnet new list func
To search for the templates on NuGet.org, run:
   dotnet new search func


For details on the exit code, refer to https://aka.ms/templating-exit-codes#103

Error creating project template
```

I've tried resintalling core tools, but still experiencing the same issue. 

Also tried just running `func init`, but ran into the same error. 

Running `func --version` returns the version, so it's strange to me why `func` isn't recognized.

### Steps to reproduce

Create a new function project using `func init` and core tools version `4.0.7030`

**Comment by mattchenderson** [comment]
After debugging with Lily, we determined that this was an issue with .NET 9.0.202. This is on an M1 Mac, with the Core Tools initially installed through Homebrew (though also reproduced with an npm installation).

The root of this seems to be how the .NET templating engine is handling the path. We observed the following when attempting to run the same command that the Core Tools was (via the `--debug` flag):

```cli
dotnet new --install "/usr/local/Cellar/azure-functions-core-tools@4/4.0.7030/templates/net-isolated/projectTemplates.4.0.5051.nupkg" -v diag
[2025-05-01 16:21:19.535] [Debug] [Template Engine] => [Execute]: Execute started
Warning: use of 'dotnet new --install' is deprecated. Use 'dotnet new install' instead.
For more information, run:
   dotnet new install -h


[2025-05-01 16:21:19.539] [Debug] [Microsoft.TemplateEngine.Edge.TemplateConstraintManager] => [Execute]: Found 5 constraints factories, initializing.
[2025-05-01 16:21:19.540] [Debug] [MSBuildEvaluator] => [Execute]: Output directory is: /usr/local/Cellar/azure-functions-core-tools@4/4.0.7030/templates/net-isolated.
[2025-05-01 16:21:19.540] [Debug] [MSBuildEvaluator] => [Execute]: Project full path is: <null>.
[2025-05-01 16:21:19.542] [Debug] [MSBuildEvaluator] => [Execute]: Found project files: .
[2025-05-01 16:21:19.542] [Debug] [MSBuildEvaluator] => [Execute]: No project found.
The following template packages will be installed:
   /usr/local/Cellar/azure-functions-core-tools::4/4.0.7030/templates/net-isolated/projectTemplates.4.0.5051.nupkg


[2025-05-01 16:21:19.601] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: /usr/local/Cellar/azure-functions-core-tools is not a local NuGet package.
[2025-05-01 16:21:19.602] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: /usr/local/Cellar/azure-functions-core-tools is not a valid NuGet package ID.
[2025-05-01 16:21:19.602] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: 4/4.0.7030/templates/net-isolated/projectTemplates.4.0.5051.nupkg is not a valid NuGet package version.
/usr/local/Cellar/azure-functions-core-tools::4/4.0.7030/templates/net-isolated/projectTemplates.4.0.5051.nupkg is not supported.


[2025-05-01 16:21:19.628] [Debug] [Template Engine] => [Execute]: Execute finished, took 93 ms
For details on the exit code, refer to https://aka.ms/templating-exit-codes#106
```

Notably, the `@` symbol from the original path seems to be replaced with `::`, and then the system seems to be splitting along that. If we moved to that directory and used a relative path, the installation worked as expected. The package then was described with `::` separating the package name and the version, which aligns with what we see here.

We also reset the state there and uninstalled .NET SDK 9.0.202, meaning a .NET 8 version was engaged. That also worked.

Using a Mac M2, I see the following:

| .NET SDK version | Behavior |
|-|-|
| 9.0.102 | No repro - works as expected |
| 9.0.200 | Observed issue |
| 9.0.202 | Observed issue |
| 9.0.203 (latest) | Observed issue|

This feels like a .NET SDK problem that has not yet been addressed. I'll need to look to see if this has already been reported somewhere and link things together there.

**Comment by mattchenderson** [comment]
I did a diagnostic trace using 9.0.102 as well, and that preserves the `@`. Relevant sequence:

```cli
dotnet new install "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.7030/templates/net-isolated/projectTemplates.4.0.5051.nupkg" -v diag   
[2025-05-01 16:01:20.818] [Debug] [Template Engine] => [Execute]: Execute started
[2025-05-01 16:01:20.820] [Debug] [Microsoft.TemplateEngine.Edge.TemplateConstraintManager] => [Execute]: Found 5 constraints factories, initializing.
[2025-05-01 16:01:20.821] [Debug] [MSBuildEvaluator] => [Execute]: Output directory is: /Users/mch/Downloads/ctrepro.
[2025-05-01 16:01:20.821] [Debug] [MSBuildEvaluator] => [Execute]: Project full path is: <null>.
[2025-05-01 16:01:20.822] [Debug] [MSBuildEvaluator] => [Execute]: Found project files: .
[2025-05-01 16:01:20.822] [Debug] [MSBuildEvaluator] => [Execute]: No project found.
The following template packages will be installed:
   /opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.7030/templates/net-isolated/projectTemplates.4.0.5051.nupkg


[2025-05-01 16:01:20.866] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: /opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.7030/templates/net-isolated/projectTemplates.4.0.5051.nupkg is identified as the local NuGet package.
```

**Comment by badsyntax** [comment]
Just chiming in to confirm, seeing this issue on my M1 Mac using `9.0.200`. A quick workround is to:

1. `dotnet new globaljson`
2. Edit `global.json`, change sdk version to eg `8.0.203` or `9.0.102`
3. `func init myproject --worker-runtime dotnet-isolated --docker --target-framework net9.0`

**Comment by valters-tomsons** [comment]
Still happening with core tools `4.0.7317`, workaround above does not help.

Edit: you need to set the **exact** 8.x.x SDK version that's listed when running `dotnet --list-sdks`

**Comment by liliankasem** [comment]
I believe the fix from .NET is now out, templates should be working again with version `9.0.301` onwards. I just validated this on my MacBook (arm64 - M3):

```
> dotnet --version
9.0.301

> func init LocalFunctionProj --worker-runtime dotnet-isolated --docker --target-framework net8.0

Writing /Users/me/source/functions/testdnitemplates/LocalFunctionProj/.vscode/extensions.json
Writing Dockerfile
Writing .dockerignore
```

As @mattchenderson mentioned, this is an issue with .NET and not Core Tools so any Core Tools version should still work. Will close the issue once I confirm this is working for other folks aswell.

**Comment by joetossell** [comment]
Unfortunately not fixed on my MacBook (arm64 - M4).
https://github.com/Azure/azure-functions-core-tools/issues/4399#issuecomment-2878848921 works

```
> dotnet --version
9.0.301
> func init LocalFunctionProj --worker-runtime dotnet-isolated --docker --target-framework net8.0
No templates or subcommands found matching: 'func'.
Did you mean one of the following templates?
   dotnet new grpc
   dotnet new mvc
   dotnet new sln
   dotnet new nunit
   dotnet new xunit

To list installed templates similar to 'func', run:
   dotnet new list func
To search for the templates on NuGet.org, run:
   dotnet new search func


For details on the exit code, refer to https://aka.ms/templating-exit-codes#103

Error creating project template
```

**Comment by liliankasem** [comment]
Hi @joetossell - thanks for sharing. Makes me wonder if there is a second underlying issue here? 

What happens when you run `dotnet new list func`? Do you see any func templates installed?

```
> dotnet new list func
These templates matched your input: 'func'

Template Name                  Short Name  Language  Tags
-----------------------------  ----------  --------  ----------------------------------------------
Azure Functions                func        [C#],F#   Azure Functions/Solution
DurableFunctionsOrchestration  durable     [C#]      Azure Function/Durable Functions Orchestration
```

Behind the scenes the func cli runs `dotnet new install Microsoft.Azure.Functions.Worker.ItemTemplate` (and .ProjectTemplates) then tries to create a new project using that template. Do you have any issues running that manually (that meaning templates install followed by `dotnet new func`)

Finally, if you uninstall and reinstall core tools, do you run into the issue still? And if so, which version?

**Comment by earloc** [comment]
> Hi [@joetossell](https://github.com/joetossell) - thanks for sharing. Makes me wonder if there is a second underlying issue here?
> 
> What happens when you run `dotnet new list func`? Do you see any func templates installed?
> 
> ```
> > dotnet new list func
> These templates matched your input: 'func'
> 
> Template Name                  Short Name  Language  Tags
> -----------------------------  ----------  --------  ----------------------------------------------
> Azure Functions                func        [C#],F#   Azure Functions/Solution
> DurableFunctionsOrchestration  durable     [C#]      Azure Function/Durable Functions Orchestration
> ```
> 
> Behind the scenes the func cli runs `dotnet new install Microsoft.Azure.Functions.Worker.ItemTemplate` (and .ProjectTemplates) then tries to create a new project using that template. Do you have any issues running that manually (that meaning templates install followed by `dotnet new func`)
> 
> Finally, if you uninstall and reinstall core tools, do you run into the issue still? And if so, which version?

Just ran into the same issue again. Installed latest `func`, now on 
` 4.0.7512 Commit hash: N/A +8be8cc84f6ad64c784e083bf4da7fa381bdd3449 (64-bit)`.
```
.NET SDK:
 Version:           9.0.301
 Commit:            a596cd22e2
 Workload version:  9.0.300-manifests.e42facbb
 MSBuild version:   17.14.5+edd3bbf37
```

running `dotnet new list func` did not resolve any templates:
```
No templates found matching: 'func'.

To search for the templates on NuGet.org, run:
   dotnet new search func
```

Doing
- `dotnet new install Microsoft.Azure.Functions.Worker.ItemTemplates`
- `dotnet new install Microsoft.Azure.Functions.Worker.ProjectTemplates`
manually did the trick.

**Comment by barkinb** [comment]
@earloc Thank you for providing a solution

you missed the 'j' in ProjectTemplates last line 
dotnet new install Microsoft.Azure.Functions.Worker.ProectTemplates

**Comment by earloc** [comment]
> @earloc Thank you for providing a solution
> 
> you missed the 'j' in ProjectTemplates last line 
> dotnet new install Microsoft.Azure.Functions.Worker.ProectTemplates

 thx, fixed it.

**Comment by anthonychu** [comment]
@liliankasem FYI ran into this on M1 mac with 4.3.0. Had to use @earloc's solution here to manually install https://github.com/Azure/azure-functions-core-tools/issues/4399#issuecomment-3061682342

**Comment by trevor-the-developer** [comment]
This issue is also happening on a fresh Fedora Core 43 Linux distro with .NET 10, 9 and 8 SDK's installed on the host machine and Azure Functions Core Tool installed inside a Distrobox container (tried both Debian and Fedora Core 43 based images).  The same issue and I was able to narrow it down to the node wrapper being wrong but adjusting this didn't seem to help.

```
func init JsonExporterFuncApp --worker-runtime dotnet-isolated --target-framework net9.0

No templates or subcommands found matching: 'func'.
Did you mean one of the following templates?
   dotnet new grpc
   dotnet new mvc
   dotnet new nunit
   dotnet new xunit
   dotnet new sln

To list installed templates similar to 'func', run:
   dotnet new list func
To search for the templates on NuGet.org, run:
   dotnet new search func


For details on the exit code, refer to https://aka.ms/templating-exit-codes#103

Error creating project template
```

Host specification:

Dell Precision 5550 i9 Laptop with 64GB Ram, 512GB nVME drive running Bazzite Linux (Fedora Core 43 based) distro, Azure CLI hosted inside a Distrobox container, .NET SDK and tooling installed on the host via the Microsoft installer script (and some manual mapping done to resolve Rider paths).

Azure Functions Core Tool was installed via script in Debian and npm install method for FCOS43 images but the same issue (func on its own works fine spits out the usual default long command message).

**Comment by trevor-the-developer** [comment]
> This issue is also happening on a fresh Fedora Core 43 Linux distro with .NET 10, 9 and 8 SDK's installed on the host machine and Azure Functions Core Tool installed inside a Distrobox container (tried both Debian and Fedora Core 43 based images). The same issue and I was able to narrow it down to the node wrapper being wrong but adjusting this didn't seem to help.
> 
> ```
> func init JsonExporterFuncApp --worker-runtime dotnet-isolated --target-framework net9.0
> 
> No templates or subcommands found matching: 'func'.
> Did you mean one of the following templates?
>    dotnet new grpc
>    dotnet new mvc
>    dotnet new nunit
>    dotnet new xunit
>    dotnet new sln
> 
> To list installed templates similar to 'func', run:
>    dotnet new list func
> To search for the templates on NuGet.org, run:
>    dotnet new search func
> 
> 
> For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
> 
> Error creating project template
> ```
> 
> Host specification:
> 
> Dell Precision 5550 i9 Laptop with 64GB Ram, 512GB nVME drive running Bazzite Linux (Fedora Core 43 based) distro, Azure CLI hosted inside a Distrobox container, .NET SDK and tooling installed on the host via the Microsoft installer script (and some manual mapping done to resolve Rider paths).
> 
> Azure Functions Core Tool was installed via script in Debian and npm install method for FCOS43 images but the same issue (func on its own works fine spits out the usual default long command message).

Just resolved my issue I had to install some missing templates and ensure the `func` command was exported to the host:

```
# Install the Azure Functions Worker templates for .NET 9 isolated
dotnet new install Microsoft.Azure.Functions.Worker.ProjectTemplates

# Also install the WebJobs templates (sometimes needed)
dotnet new install Microsoft.Azure.WebJobs.ProjectTemplates

# Verify installation
dotnet new list | grep -i "azure.*func"
```
